### ISSUE TITLE
Export CE values only for transition lists where CE is available for all transitions

### ISSUE THREAD

**Issue by nilshoffmann** [lifs-tools/lipidcreator#16]
The current behaviour of LipidCreator when transitions lists that contain CEs for a subset of transitions only, setting the remaining ones to -1, is not well defined. It may be necessary to not export the CE column at all, once transitions are included that have no CE set. See #15 for more details on the discussion. Exporting -1 values as of now may cause vendor-dependent interpretation of what that value actually means. We should carefully check that this does not have unwanted side-effects. Unfortunately, we may not be able to avoid this issue completely, since users may export and transfer multiple transitions lists from LipidCreator to Skyline, thereby mixing transitions with proper CEs and ones without any CE.

**Comment by dominik-kopczynski** [comment]
Bug is fixed and will be available in the new release 2.0 which we currently prepare.

**Comment by nilshoffmann** [comment]
Fixes were cherry picked from v2.0 branch into master for inclusion in LipidCreator 1.2.1 bugfix release.
