### ISSUE TITLE
save project space automatically

### ISSUE THREAD

**Issue by dominik-kopczynski** [lifs-tools/lipidcreator#8]
I was surprised that my ‘search settings’ were not saved automatically!

Incl my recent ‘manage heavy isotopes’ for a particular lipid class…

**Comment by nilshoffmann** [comment]
Should we save periodically?
Or just when the user wants to close the Window?
Or if the user clicks on "Review Lipids"?

**Comment by chemice** [comment]
What about a warning message when user wants to close the Window? To remind them export the project/setting.

**Comment by dominik-kopczynski** [comment]
That's a good idea, I can implement it very easily :-)

**Comment by dominik-kopczynski** [comment]
Introduced a Yes / No / Cancel dialog when closing LipidCreator.
