### ISSUE TITLE
crash when making 2M transitions

### ISSUE THREAD

**Issue by dominik-kopczynski** [lifs-tools/lipidcreator#9]

**Comment by nilshoffmann** [comment]
Could this be a result of the XLSX export and the library we use for that?
Does this occur with the csv / tsv export as well?

**Comment by chemice** [comment]
This was the result of .xlsx export.

**Comment by dominik-kopczynski** [comment]
The maximum number of rows in Excel is 1048576 [1]. How should we deal with it? One way is to warn the user that he / she is exceeding the max number of rows when exporting and abort the export. Other ideas?

[1] https://www.tutorialspoint.com/excel/excel_rows_columns.htm

**Comment by nilshoffmann** [comment]
Yes, I think warning is a good idea. We should then save the data in csv, since that is something that Excel may be able to read? 
Or would it make sense to split the output into ceil(n/1048576) partial xlsx files?

**Comment by chemice** [comment]
The reason to have Excel as output format was about the fragment names. If you save the data in csv, but open the file with Excel, many fragment names will mess up (e.g., name start with "-"). For many users, open data in Excel is kind of default. 
I think it would be useful to split the excel output when exceed 1048576.

**Comment by dominik-kopczynski** [comment]
Or let the user decide, if row count exceeds 1M, a dialog pops up with the question: "split or cancel?"
